[package]
edition = "2021"
name = "examples"
version = "0.1.0"

[dependencies]
blockifier = { git = "https://github.com/keep-starknet-strange/blockifier", branch = "snos/callinfo-clone", features = ["clone", "testing"] }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", features = ["extensive_hints", "cairo-1-hints"] }
clap = "4.5.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.105", features = ["arbitrary_precision"] }
snos = { path = "../../" }

[[bin]]
name = "hint_tool"
path = "src/main.rs"
