[package]
name = "prove_block"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
blockifier = { workspace = true }
cairo-lang-starknet-classes = { workspace = true }
cairo-lang-utils = { workspace = true }
cairo-vm = { workspace = true }
clap = { workspace = true }
pathfinder-common = { workspace = true }
pathfinder-crypto = { workspace = true }
pathfinder-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
starknet-os = { path = "../../starknet-os" }
reqwest = "0.11.27"
tokio = { workspace = true }
starknet_api = { workspace = true }
starknet = "0.11.0"
starknet-types-core = "0.1.3"
log = { workspace = true }
env_logger = { workspace = true }
futures-core = "0.3.30"
async-stream = "0.3.5"
